export type TechnologyType =
  | 'JavaScript'
  | 'TypeScript'
  | 'React'
  | 'Redux Toolkit'
  | 'HTML5'
  | 'CSS3'
  | 'SCSS'
  | 'BEM'
  | 'Fetch'
  | 'REST API'
  | 'Git'
  | 'Vite'
  | 'ESLint'
  | 'Prettier'
  | 'Next'
  | 'Tailwind'
  | 'Bulma'
  | 'Radix UI'
  | 'Swiper';